name:
  firstname: sin
  lastname: youngjin
  password: "{cipher}9357c645da1f863891a6dbb93399916413841cc086c49d7821f8b7ccd437a192"
  message: i am default

spring:
  datasource:
    url: jdbc:postgresql://database:5432/testdb
    username: postgres
    password: p0stgr@s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE