name:
  firstname: sin
  lastname: nari
  password: "{cipher}3376eee3887c9f11c1593536ce075dd1bab11eba5fbdab9f9348da9e06f7c3fa"
  message: i am dev

spring:
  datasource:
    url: jdbc:postgresql://database:5432/testdb
    username: postgres
    password: p0stgr@s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://authserver:8901/auth/user

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.example: DEBUG