name:
  firstname: sin
  lastname: youngjin
  password: "{cipher}9357c645da1f863891a6dbb93399916413841cc086c49d7821f8b7ccd437a192"
  message: i am default

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://auth-database:3306/testdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: nuguri
    password: bom
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework.web: WARN
    com.netflix: WARN
    com.example: DEBUG